apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: grim
resources:
  - namespace.yaml
  - sealedsecret.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - networkpolicy-default-deny-ingress.yaml
  - networkpolicy-allow-from-ingress-nginx.yaml
labels:
  - pairs:
      app.kubernetes.io/name: grim-backend
