apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: web
labels:
  - pairs:
      app.kubernetes.io/name: web
    includeSelectors: true
resources:
  - namespace.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - hpa.yaml
  - pdb.yaml
  - networkpolicy-default-deny-ingress.yaml
  - networkpolicy-allow-from-ingress-nginx.yaml
