apiVersion: v1
kind: PersistentVolume
metadata:
  name: alloy-data
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: alloy-local
  hostPath:
    path: /var/lib/alloy
    type: DirectoryOrCreate
