---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alloy-basic-auth
  namespace: alloy
spec:
  encryptedData:
    auth: AgAeeXWX4LR8Kcf77Vm51Xhlbjo2er2FOgFZY9+FeK3+MbzpGu8tXYZ3HyKIpca5LabaQRw7/6ekLlQRGA+z0qOJeT+1sI+M+TGhECvygz1vMPNXWjC0g99TjBw5bDxelLO3cOOJmdkLeydSA+rtRsZt5P3h3v1qdJ55A4YI3afNJ7JVR/JE8O8K0eDqJ32iVf/4Vn6TCz/XShhDPJ6tTdEMAfr+UDwoJ5l8CxDd1LQR0uFFTp7bmaqq4bMW/ueZq4ex1Ugyg9vzD6f0O4HtiugcV6xJK4lF7NzhK1sAhJ3MVzIB2e9snYaiGbtsfv4BUcUwf8OuiTpevgERvhdBjdrDoL3ealiT8pB+srDOwscAmw90PwiiU9d+Tx4Cof6MVEGyaersl0tTwiTejt5gXbEH9aWhtEAJ4rJoBMmurGbjbSHUW+FateyldKSFhWb3cFsa/PV0xkp/BqgzOwIJVY7NXNfEQDle4OsMNXNHAeahDd1f+QhSw2/iLK70RmIenEawzO2xfKlw/98NGe3HUq6fIJ/SkF3LzGqprtBHVXBl7uqfjt/DAEZmMD9njfocxSYkb0qM0dyHNGxVdzqNY6ANZwXamEl+UlhX4R7IUhGtPog5KePjT9r0GSS2cqb1VSOtCcysPvGpShGGXrCsWauWLPqiBtmxGFeQvrQLIOOWouoEGuH7cveT/DaXqt+xHpZ/8IORJl7+15+yydFdv3YQLCm2QGF0Oks22zxUpHjksIaFNbW84oVrLrvByP8zbaWK
  template:
    metadata:
      name: alloy-basic-auth
      namespace: alloy
