apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: grafana
data:
  datasources.yaml: |
    apiVersion: 1
    prune: true
    datasources:
      - name: Prometheus
        uid: prometheus
        type: prometheus
        access: proxy
        url: http://prometheus.prometheus.svc.cluster.local/prometheus
        isDefault: true
        jsonData:
          httpMethod: POST
          prometheusType: Prometheus
          prometheusVersion: 3.11.2
          timeInterval: 30s
      - name: Loki
        uid: loki
        type: loki
        access: proxy
        url: http://loki.loki.svc.cluster.local:3100
        jsonData:
          maxLines: 1000
