apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-data
  namespace: grafana
spec:
  storageClassName: grafana-local
  volumeName: grafana-data
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
