---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-credentials
  namespace: grafana
spec:
  encryptedData:
    GF_SECURITY_ADMIN_PASSWORD: AgAWym3fCElJtF4eD/I6kJYVOs1XpEsTfoROtZ2SZ8OYBTdUII09UFok+DnqgIAla9VZp1kNqRxUwi695tUSHin1fHJ6iwo/WBq0G6LLm7VrRDrivu0FLp+VeC/AwfWDOwjx33NPlF2+RgQfPt6EhL1iOAQv5itsVIQSfs/PIMzqHBXqmLcPqJXaMh4PJ2vMbVNnEF4BudUZjYsTiqgE6GU2XGqx4+9aAYkYCu01Vd03A0XLRsx9tBiDTxCSfNTj2iuT09sgBsW0Fu6QgGJQtTozIQQPvbBq1laYkE7DFbnb1yChSAQrffnDA0XUj9SxX4YwHY+2FTGh8bIYTzl9g3/zeFM2QD1ttwtFMOF25XKm52R5EM+WeH5YzfFIuXHOFfvNf1wmjEtaXRRdktHd3tvtp3ZQ9BlusNkIvnKGy8p+CbZNuaJ9Ax0DnnZQiL7eF4zYwb0C1bZsxWC5If6mDhxweIKJm1XoVNOBJqT7pKEj/ZxatPq9q8k3p4qONvY/0LnN5n1M2vZ0ivnJifH9GrItWC2xWKW0hBJlhkZWTT7uxtQNw+D3AFJzbJk7hAfonyvimlUgnDgeEpQQnExoRazT8GCIcF3eg520A8rX6YD085P4SOh6oD47bsTSIyztCRa9XBU7zK/meLR0b9yzHtDpowIfVnue0c5SOZrdgKjR/wNAT6eyKXx4Y3cX2qdmulAY6/v5SbpBECU=
    GF_SECURITY_ADMIN_USER: AgDTLTwyTiTpR8TZRsYbFh5GtZXK1lQ1A0V9+qkBu1ZvjI6WJD3BcpO0445SS5XMQUuftXnOLsc28SNDGiNwHDRpeLT4JQAM+U1dzwB2luAS+wgR6LRE/Al8eVLMPZVQ0bjbv6LpKvHFDCaAmHsbR0JD+BuZLy4b/TcPPuoCk6RpLyrRnOv//iL1UHrD4mkJs1AR+vLQ8psWiaeFVbyKDh/aN9p+uNzskCvwXUiTtgR0kGo+uVUShGEFHZEecO0ySTQjM+Jil/Pc5s7sekaEhSau+545SDKQbp7RQ+0tEwSWfo2YAPsKSHX9Qhy5a2b4TouEBU7uhRUWuKtnm/umEdDUXj1ii285GFjVQcic5q/l2eOKerOtnJPUR2L8EFQ334lHvDlMSJWd/wf5aerFW1w7TGoILSYlrNO9t78zSoDldxS2Lz/vCq8Gd1rVY28kDcytS1udt+TY05KRZhH0dGg8AoJyWApkz6m3rsgi1K11Vkk+9ZhzVej2E9Bk8xWqSVrYsWXqxDD+sn2GeEQwqn2jL0Vbpz3MwrbFbMP3BHTJFiXwjysMWUCCe1Bl3duiKdgZ2iwKIbA/0qRd+j1KmYwPr/26dfn3gnEaNLIaKzOShBupfYqJfy7m09XOwxNj52a0cSUbDz46rK/b++HGGC+G5xxUH11z6kbrv+WBQ6quEWZbZLEEvwAE+MZKkKIqU9YL/FqbTKn306IfYQ==
  template:
    metadata:
      name: grafana-admin-credentials
      namespace: grafana
