---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: headlamp-basic-auth
  namespace: headlamp
spec:
  encryptedData:
    auth: AgARCkF35FgeGJf+Ul5OGkjsSmV6Gmc7sya6ucv85jurjj7V6mhHZrwl7WVl0/GdoHkflJrnsSjqCkf9NFGLPCHRdJwMEz/Tpmn4s6yczW9IO4VvQYRJazBKOB9lqsiABJ/bhHKYnW75m8vKivKeo2lO/kLPKU4mos0V5/Gce+mTJtocMyZoabhzpFgPFTZ9uySrWpVXVgovC8FkhFs3HdnYmpzo4elwfvFx3XpUJacRt9iQ/7a7lZ/52Edxu3o5aAUFCy7S1JeX39ZeA88Z7/uyT0i3EW9dncxMNxCrwV6wIjsDleCcZiM+IGF6Ombmh5kgR9LLfiR1HcvbH95cnQ2X1azOcAV07MhFNk1FMl9bv2UMyv5tStwQ2EnRD+LCDPWZ12uVil2QbjpIf7eWk+NjL4TdbIWbLew3JXBON37Mi2yQ/4JBupt7ogvXl8ApkGdNUj7NQUeKl90Pua0zbYxEvgUMZrqLhs0RbFbGHT2QgLS9737SBGwPXGXbjsnUc2qC06s2eT61QZxwizXegl7q5V2igsP+hd6cP862pJ91Y7rF2dKbJQrjQZhXD5HNG/h98y2JyMbAwz/98EAc74sktPPK/pv2eiT01K84f03S6ellFuJHtgg+w+00zbBotcJQO1hhyj1cgnES15R+n14QqzR0LHl9n5M5Ne7ieK4+4niw1l7YEEJCkJIRODUcRGy5f3ETpcfIZkZE46BN7Ct514Xw5o7ofw+gRHwtbXYcsGvtb8Dz0MlqgBMq76UeL4+9bQ==
  template:
    metadata:
      name: headlamp-basic-auth
      namespace: headlamp
