apiVersion: v1
kind: Secret
metadata:
  name: argocd-secret
stringData:
  accounts.jungxuanlow.password: "$2b$10$ugGjpPl0GtzAlM4vFPjewOCVjICoijksWXxhI79GlhaO4p1xdp/ju"
  accounts.jungxuanlow.passwordMtime: "2026-04-24T18:03:00.767847Z"
