apiVersion: v1
kind: Secret
metadata:
  name: argocd-secret
stringData:
  accounts.jungxuanlow.password: "$2b$10$jw1ZzFIXulb4uKC0yjYsHe842OA1yGPvcvFQiotMvElMZUWjr9e9."
  accounts.jungxuanlow.passwordMtime: "2026-04-25T10:50:23.974084Z"
