apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grim-backend
  namespace: argocd
  labels:
    app.kubernetes.io/name: grim-backend
spec:
  project: default
  source:
    repoURL: git://gitops-git.argocd.svc.cluster.local/gitops.git
    targetRevision: main
    path: apps/grim-backend/overlays/production
  destination:
    server: https://kubernetes.default.svc
    namespace: grim
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
