apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-from-grafana
  namespace: loki
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: loki
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: grafana
      ports:
        - protocol: TCP
          port: 3100
