apiVersion: v1
kind: PersistentVolume
metadata:
  name: loki-data
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: loki-local
  hostPath:
    path: /var/lib/loki
    type: DirectoryOrCreate
