apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loki-data
  namespace: loki
spec:
  storageClassName: loki-local
  volumeName: loki-data
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
