---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: loki-basic-auth
  namespace: loki
spec:
  encryptedData:
    auth: AgB9tnOSP70CL/B00MCcFWDP+3YYUVOxBMSfGX8M20tF5/qUTGRbdQZSsEKnuW/u6VK76SlBXgYMRdNQJh4QSjGP4TyrMiE1vWVX4843C2CV23tXqQCUzrbb7nHnWZKytF7vbbA3D0/Zl3pL4e7+D0BC4/X/e3ClnyiRR5pAHkSujmAtsTGNE00DOkSagUZGyefgBYa7WBC0or7AUgINzNmJDU6yIGJzMGgN2IY2vZzpJiZGiZEW/IFCoH4qxMbjCl9NB52ePajTZO6b0Wg3uKb7OZd8XDlVzWQTqoxea7uWYFCw9dCRULS7fT7F1sdDZRLHNcXeYlnyuelqMj9OcBEkaJiVFdorA9AcWKUIlFEw4JRR00yTeLVKrc0Hadr+ZADpfMd5LsGbtVOTQ/jOa7scZYdKBkiIRKwu85I2EPy1iQZzjEsQc19N1XUvIllTm2A+BakyeJuRBIxJdscLE5960aZU8jAGsbg7C/9uIWt2pvp/iRWR4yBIALSYrpDJEjaHZMzXxx3I0JcIxVCUAK2RbnuQvpLyxStcJI8tu60GJ4ry2VKOUzxBVL4qrKetXlJpAfdw5OmgP4GAiy84J58Mc6WbgBaue1hThHouKWCxpUIhs6U15gg9briF3fYyv16zcO+eEKdIyReK8CF7j+6ZEIjRv0A/+20Frr9dJJbBwInb3R5N7sO2DY4Nwp/37MMc57kL97wZ/GVbq8CVifERoRnJZ208eGKwGdMMXFlFsudV+FtbmwkDjoZQQwzktVXQ
  template:
    metadata:
      name: loki-basic-auth
      namespace: loki
