apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - ingress.yaml
  - ingress-api.yaml
  - networkpolicy-allow-api-from-ingress-nginx.yaml
patches:
  - path: deployment-patch.yaml
