apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - controller.yaml
images:
  - name: docker.io/bitnami/sealed-secrets-controller
    newName: ghcr.io/bitnami-labs/sealed-secrets-controller
    newTag: 0.36.6
