---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: prometheus-basic-auth
  namespace: prometheus
spec:
  encryptedData:
    auth: AgDbZLFBD7zys5f0Dtd4N64irHRlyxVnLQItAQLh3E8Qyk04xs6BiNrxhHdP1QzWPnU3N8iuXclGqxNuEtwpffJaL/rMPXaq0BHjGs3AxmVfO6JcOuCgyf8OWIX+xdPUHTPyHHlN8Zk3qBkUIq8IeAqXJGUEqEAclJI669C4oHas77XvrCGKywmDZBhJuvbK8WiEHmGWKnfkIEHbhvPUr+OI7g/UrVkctQ//KWaN1eHhh7kU20tM0pAOax6pjV2/SpU/0BiFCsQAu3olWs0GOf1wbsc12fosdUvwdfDr9PC5vVKn4ibLb3yrN5R8dVdLFSDD0Z8W3BdHNdQb9aunx/S0N/eFEnIvrIY7JvEEuVNEZYQ0aWS3W9+ks/9mg0ryO9jlMm1knGpVliZ0I+ZGWtzP3+KzrVIxjon3FK+YmxS8n/FtYxm50dO8ILYdnrAQZW+BGel1Nu9qpnwENIK6CRnyzHZ2Oatq+NE7Twh/9TCD3nZ6fnVuaUhXfWSnsUKXwA5qKsI1xzrjNUyWAu88mrSfTgTaUjRM9HpwwNBrbHWC1g5V8XMbzxx2xtNa5mHr9HQoibF4Mxb1QUQ1CpGNBg6Hd4LZ8rzKeLvjPNUeDrJPMdl80FwCOUIspt/7CmX/jeKonhWLkCAy//Aw3EoAYpXQyIbkg+L1uIJObDJCLUsBbxT2EDJ2y7Dke1a0IB1pl+Cc0FHzDVUbNskc7cCLAfkkbvRVy0bKv0u/E39iYmRk5g5AXOAwblniOv388WOfnH9/9A==
  template:
    metadata:
      name: prometheus-basic-auth
      namespace: prometheus
