apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grim-backend
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  tls:
    - hosts:
        - lowjungxuan.dpdns.org
      secretName: grim-backend-tls
  rules:
    - host: lowjungxuan.dpdns.org
      http:
        paths:
          - path: /backend/(.+)
            pathType: ImplementationSpecific
            backend:
              service:
                name: grim-backend
                port:
                  number: 80
