apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - ingress-root-redirect.yaml
  - ingress-openapi.yaml
patches:
  - path: deployment-patch.yaml
  - path: ingress-patch.yaml
