apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: minio
resources:
  - namespace.yaml
  - pv.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - networkpolicy-default-deny-ingress.yaml
  - networkpolicy-allow-from-grim-backend.yaml
  - networkpolicy-allow-console-public.yaml
