apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-data
spec:
  storageClassName: minio-local
  volumeName: minio-data
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
